language: java
sudo: false

addons:
  artifacts:
    bucket: unidata-tds-tests
    paths:
      - $TRAVIS_UPLOAD_PATH
    target_paths: Travis/$TRAVIS_BRANCH-$TRAVIS_BUILD_NUMBER/$TRAVIS_JOB_NUMBER

jdk:
  - oraclejdk8

env:
  matrix:
    - TASK="build"
    - TASK="docs"

before_install:
  - if [[ $TASK == "docs" ]]; then
      gem install asciidoctor coderay;
    fi

# Skip the installation step entirely; we don't need it for Gradle builds.
# https://docs.travis-ci.com/user/customizing-the-build#Skipping-the-Installation-Step
install: true

script:
  # If we need to do an IDV build, run the script
  - if [[ $TASK == "build_idv" ]]; then
      travis/build_idv.sh;
    elif [[ $TASK == "docs" ]]; then
      echo Building docs;
      cd docs/website;
      ./adoc2html.sh 2> build.log;
      if [ -s build.log ]; then
        echo Doc build produced errors:;
        cat build.log;
        false;
      fi;
    else
      echo If available, test report at;
      echo http://unidata-tds-tests.s3.amazonaws.com/Travis/${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}/${TRAVIS_JOB_NUMBER}/index.html;

      JNA_LIB=-Djna.library.path=$TRAVIS_BUILD_DIR/travis/lib/ubuntu-12.04.5-amd64;
      CONTENT_ROOT=-Dtds.content.root.path=$TRAVIS_BUILD_DIR/tds/src/test/content;
      DOWNLOAD_DIR=-Dtds.download.dir=/tmp/download;
      SYSTEM_PROPS="$JNA_LIB $CONTENT_ROOT $DOWNLOAD_DIR"

      ./gradlew $SYSTEM_PROPS --info --stacktrace testAll;
    fi

# See https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
